### ISSUE TITLE
求问使用的pdf软件

### ISSUE THREAD

**Issue by SydCS** [CHENHUI-X/Deep-Learning-Classic-Papers#1]
想问一下up平时用的是什么软件阅读论文pdf并进行批注，觉得很美观，谢谢！

**Comment by CHENHUI-X** [comment]
> 想问一下up平时用的是什么软件阅读论文pdf并进行批注，觉得很美观，谢谢！

之前在用极速pdf，现在在用wps。

**Comment by SydCS** [comment]
ok 感谢！
